// Auto-generate a short session title from the first user message + first
// assistant response. Model choice: an explicit modes.json:autoTitle override
// wins; otherwise the current session's active model is used (so titles match
// the model you're chatting with). Falls back to code-mode's model, then a
// cheap GPT, only when there's no usable active model. Runs once per session.

import { completeSimple } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { ModeState } from "./state";

const titledSessions = new Set<string>();

// Title language follows the VS Code extension's hmm-code.language setting,
// passed in as HMM_CODE_LANG ("en"/"ko") when Pi is spawned by the .vsix. In
// the standalone TUI (no env) it falls back to matching the conversation.
function titleSystemPrompt(): string {
	const lang = process.env.HMM_CODE_LANG;
	const langLine =
		lang === "ko"
			? "Always write the title in Korean."
			: lang === "en"
				? "Always write the title in English."
				: "Use the user's language.";
	return (
		"You generate a very short (3–7 words) descriptive title summarizing what the user is trying to do. " +
		langLine +
		" Respond with ONLY the title — no quotes, no markdown, no preamble, no trailing punctuation."
	);
}

// Last-resort cheap GPT candidates, tried only when there's no active or
// code-mode model. First one found + authed wins. To force a dedicated naming
// model regardless of the active one, set modes.json:
//   "autoTitle": { "provider": "openai", "id": "gpt-4o-mini" }
const GPT_CANDIDATES: { provider: string; id: string }[] = [
	{ provider: "openai", id: "gpt-4.1-nano" },
	{ provider: "openai", id: "gpt-4o-mini" },
	{ provider: "openai", id: "gpt-4.1-mini" },
	{ provider: "openai", id: "gpt-4o" },
	{ provider: "openai", id: "gpt-3.5-turbo" },
];

function resolveTitleModel(ctx: any, state: ModeState): { model: any; via: string } | null {
	// Skip models that have no API key configured — they'd just error out and
	// trigger our user-message fallback anyway.
	const authed = (m: any) => {
		if (!m) return false;
		try {
			return ctx.modelRegistry?.hasConfiguredAuth?.(m) !== false;
		} catch {
			return false;
		}
	};
	// 1. Explicit override (modes.json: autoTitle) always wins.
	const override = state.autoTitleOverride;
	if (override && override.provider && override.id) {
		const m = ctx.modelRegistry?.find?.(override.provider, override.id);
		if (m && authed(m)) return { model: m, via: `override:${override.provider}/${override.id}` };
	}
	// 2. No override → use the current session's active model, so titles are
	//    generated by the same model you're chatting with and don't require a
	//    separate provider (e.g. OpenAI) to be authed.
	if (ctx.model && authed(ctx.model)) {
		return { model: ctx.model, via: `ctx.model:${ctx.model.provider}/${ctx.model.id}` };
	}
	// 3. Fallbacks for the rare case there's no usable active model: code-mode's
	//    configured model, then a cheap dedicated GPT.
	const codeRef = state.configFor("code")?.model;
	if (codeRef && codeRef !== "none" && typeof codeRef === "object") {
		const m = ctx.modelRegistry?.find?.(codeRef.provider, codeRef.id);
		if (m && authed(m)) return { model: m, via: `code-mode:${codeRef.provider}/${codeRef.id}` };
	}
	for (const c of GPT_CANDIDATES) {
		const m = ctx.modelRegistry?.find?.(c.provider, c.id);
		if (m && authed(m)) return { model: m, via: `gpt:${c.provider}/${c.id}` };
	}
	return null;
}

export function registerAutoTitle(pi: ExtensionAPI, state: ModeState): void {
	pi.on("message_end", async (event: any, ctx: any) => {
		if (event?.message?.role !== "assistant") return;

		// Don't let title generation piggyback on a turn that's also compacting:
		// it would fire a second LLM request to the (often local) session model
		// right alongside the compaction summary. Two cases:
		//   - a compaction is already in flight — the manual /compact path aborts
		//     the current turn, which finalizes this very message_end while
		//     compactInFlight is set;
		//   - context is at/over the auto-compact threshold, so the upcoming
		//     turn_end is about to compact (message_end fires before turn_end, so
		//     compactInFlight isn't set yet — check usage directly).
		if (state.compactInFlight) return;
		try {
			const pct = ctx.getContextUsage?.()?.percent;
			if (typeof pct === "number" && pct >= state.autoCompactThreshold) return;
		} catch {
			/* getContextUsage unavailable — fall through and title normally */
		}

		const sessionId: string | undefined = ctx.sessionManager?.getSessionId?.();
		if (!sessionId || titledSessions.has(sessionId)) return;

		const existing = (pi as any).getSessionName?.() ?? ctx.sessionManager?.getSessionName?.();
		if (existing) {
			titledSessions.add(sessionId);
			return;
		}

		const branch: any[] = ctx.sessionManager?.getBranch?.() ?? [];
		const firstUserEntry = branch.find((e) => e?.type === "message" && e.message?.role === "user");
		if (!firstUserEntry) return;

		const picked = resolveTitleModel(ctx, state);
		if (!picked) return;
		const model = picked.model;

		// Mark BEFORE async to prevent re-entry on subsequent message_end events.
		titledSessions.add(sessionId);

		const userText = extractText(firstUserEntry.message?.content);
		const assistantText = extractText(event.message?.content);

		// Fire-and-forget the LLM call. Awaiting it inside the message_end
		// handler holds Pi back from entering its idle state — the TUI
		// "Working..." loader stays up and the VS Code status row lingers
		// because Pi thinks our extension is still working. Detaching the
		// async work lets message_end resolve immediately; the title still
		// arrives a moment later via setSessionName, which emits
		// session_info_changed for the UI to pick up.
		void runTitleGen({
			pi,
			ctx,
			model,
			userText,
			assistantText,
		});
	});
}

interface TitleGenArgs {
	pi: ExtensionAPI;
	ctx: any;
	model: unknown;
	userText: string;
	assistantText: string;
}

async function runTitleGen(args: TitleGenArgs): Promise<void> {
	const { pi, ctx, model, userText, assistantText } = args;

	// Resolve apiKey/headers — ctx.modelRegistry.find() returns the Model
	// WITHOUT credentials (those live in AuthStorage). Pass via options.
	let resolvedApiKey: string | undefined;
	let resolvedHeaders: Record<string, string> | undefined;
	try {
		const auth = await ctx.modelRegistry?.getApiKeyAndHeaders?.(model);
		if (auth?.ok) {
			resolvedApiKey = auth.apiKey;
			resolvedHeaders = auth.headers;
		}
	} catch {
		/* silent — background job */
	}

	let title = "";
	try {
		const context = {
			systemPrompt: titleSystemPrompt(),
			messages: [
				{
					role: "user" as const,
					content: [
						{
							type: "text" as const,
							text: `Conversation so far:\n\nUser: ${userText.slice(0, 600)}\n\nAssistant: ${assistantText.slice(0, 600)}\n\nNow write ONLY the title.`,
						},
					],
					timestamp: Date.now(),
				},
			],
			tools: [],
		};
		const result = await completeSimple(model as any, context, {
			apiKey: resolvedApiKey,
			headers: resolvedHeaders,
			reasoning: "off",
			metadata: {
				chat_template_kwargs: { enable_thinking: false, preserve_thinking: false },
			},
		} as any);
		title = pickTitle(extractText((result as any)?.content));
		if (!title) {
			const thinking = extractThinking((result as any)?.content);
			if (thinking) {
				const lastLine = thinking.split("\n").filter((l) => l.trim()).pop() ?? "";
				title = pickTitle(lastLine);
			}
		}
	} catch {
		/* silent — fall through to userText pickTitle fallback */
	}

	if (!title) title = pickTitle(userText);
	if (!title) return;

	const setFn = (pi as any).setSessionName ?? ctx.setSessionName;
	if (typeof setFn !== "function") return;
	try {
		setFn(title);
	} catch {
		// Pi can throw "ctx is stale" if the session ended before our async
		// LLM call resolved (most common in --print mode). Background job —
		// failing to name the session is recoverable; silently drop.
	}
}

function extractText(content: any): string {
	if (typeof content === "string") return content;
	if (!Array.isArray(content)) return "";
	return content
		.filter((p: any) => p && p.type === "text" && typeof p.text === "string")
		.map((p: any) => p.text)
		.join("");
}

function extractThinking(content: any): string {
	if (!Array.isArray(content)) return "";
	return content
		.filter((p: any) => p && p.type === "thinking" && typeof p.thinking === "string")
		.map((p: any) => p.thinking)
		.join("\n");
}

/** Squash whitespace, strip quotes/markdown, prefer first sentence, cap 30. */
function pickTitle(raw: string): string {
	if (!raw) return "";
	let s = raw
		.replace(/\r/g, "")
		.replace(/^\s*[-*]\s+/gm, "")
		.replace(/^#+\s*/gm, "")
		.replace(/^\s*["'`「『]+|["'`」』]+\s*$/g, "")
		.trim();
	s = s.split("\n").map((l) => l.trim()).find((l) => l.length > 0) ?? "";
	const sentenceEnd = s.search(/[.?!。！？]/);
	if (sentenceEnd >= 0 && sentenceEnd < 80) {
		s = s.slice(0, sentenceEnd);
	}
	s = s.replace(/\s+/g, " ").trim();
	if (s.length <= 30) return s;
	return s.slice(0, 28).trim() + "…";
}
